-- Table: CLIENT
CREATE TABLE CLIENT (
    NCLI VARCHAR (4) UNIQUE NOT NULL PRIMARY KEY,
    NOM TEXT,
    ADRESSE TEXT,
    LOCALITE TEXT NOT NULL,
    CAT CHAR (2),
    COMPTE DOUBLE DEFAULT (0)
);

-- Table: COMMANDE
CREATE TABLE COMMANDE (
    NCOM INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    NCLI VARCHAR (6) REFERENCES CLIENT (NCLI),
    DATECOM DATE NOT NULL
);

-- Table: DETAIL
CREATE TABLE DETAIL (
    NCOM REFERENCES COMMANDE (NCOM),
    NPRO REFERENCES PRODUIT (NPRO) ON DELETE CASCADE ON UPDATE CASCADE,
    QCOM INTEGER DEFAULT (1) NOT NULL
);

-- Table: PRODUIT
CREATE TABLE PRODUIT (
    NPRO CHAR (5) PRIMARY KEY UNIQUE,
    LIBELLE TEXT NOT NULL,
    PRIX DECIMAL,
    QSTOCK INTEGER DEFAULT (0)
);